# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Analytics_e.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IsomStdDef_pb2 as IsomStdDef__pb2
import Analytics_pb2 as Analytics__pb2
import IsomSchedules_pb2 as IsomSchedules__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Analytics_e.proto',
  package='Honeywell.Security.ISOM.Analytics',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x41nalytics_e.proto\x12!Honeywell.Security.ISOM.Analytics\x1a\x10IsomStdDef.proto\x1a\x0f\x41nalytics.proto\x1a\x13IsomSchedules.proto\"\xac\x01\n\x11\x41nalyticsConfig_e2\x96\x01\n\x1f\x41nalyticsAssociatedWithSchedule\x12\x32.Honeywell.Security.ISOM.Analytics.AnalyticsConfig\x18\xa1\xf7\x36 \x03(\x0b\x32\x31.Honeywell.Security.ISOM.Schedules.ScheduleConfigB\x04\xa0\xb5\x18\x01')
  ,
  dependencies=[IsomStdDef__pb2.DESCRIPTOR,Analytics__pb2.DESCRIPTOR,IsomSchedules__pb2.DESCRIPTOR,])




_ANALYTICSCONFIG_E = _descriptor.Descriptor(
  name='AnalyticsConfig_e',
  full_name='Honeywell.Security.ISOM.Analytics.AnalyticsConfig_e',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='AnalyticsAssociatedWithSchedule', full_name='Honeywell.Security.ISOM.Analytics.AnalyticsConfig_e.AnalyticsAssociatedWithSchedule', index=0,
      number=900001, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=285,
)

DESCRIPTOR.message_types_by_name['AnalyticsConfig_e'] = _ANALYTICSCONFIG_E
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyticsConfig_e = _reflection.GeneratedProtocolMessageType('AnalyticsConfig_e', (_message.Message,), {
  'DESCRIPTOR' : _ANALYTICSCONFIG_E,
  '__module__' : 'Analytics_e_pb2'
  # @@protoc_insertion_point(class_scope:Honeywell.Security.ISOM.Analytics.AnalyticsConfig_e)
  })
_sym_db.RegisterMessage(AnalyticsConfig_e)

_ANALYTICSCONFIG_E.extensions_by_name['AnalyticsAssociatedWithSchedule'].message_type = IsomSchedules__pb2._SCHEDULECONFIG
Analytics__pb2.AnalyticsConfig.RegisterExtension(_ANALYTICSCONFIG_E.extensions_by_name['AnalyticsAssociatedWithSchedule'])

_ANALYTICSCONFIG_E.extensions_by_name['AnalyticsAssociatedWithSchedule']._options = None
# @@protoc_insertion_point(module_scope)
