# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IsomSecurity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IsomStdDef_pb2 as IsomStdDef__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IsomSecurity.proto',
  package='Honeywell.Security.ISOM.Security',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12IsomSecurity.proto\x12 Honeywell.Security.ISOM.Security\x1a\x10IsomStdDef.proto\"j\n\x03Key\x12\x38\n\x07keyType\x18\x0b \x01(\x0e\x32\'.Honeywell.Security.ISOM.EncryptionType\x12\x0b\n\x03key\x18\x0c \x01(\t\x12\x12\n\nserverPath\x18\r \x01(\t*\x08\x08\xc0\x84=\x10\xe0\x91\x43')
  ,
  dependencies=[IsomStdDef__pb2.DESCRIPTOR,])




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='Honeywell.Security.ISOM.Security.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyType', full_name='Honeywell.Security.ISOM.Security.Key.keyType', index=0,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=11,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='Honeywell.Security.ISOM.Security.Key.key', index=1,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverPath', full_name='Honeywell.Security.ISOM.Security.Key.serverPath', index=2,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000000, 1100000), ],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=180,
)

_KEY.fields_by_name['keyType'].enum_type = IsomStdDef__pb2._ENCRYPTIONTYPE
DESCRIPTOR.message_types_by_name['Key'] = _KEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'IsomSecurity_pb2'
  # @@protoc_insertion_point(class_scope:Honeywell.Security.ISOM.Security.Key)
  })
_sym_db.RegisterMessage(Key)


# @@protoc_insertion_point(module_scope)
