# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IsomUserMgmt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IsomStdDef_pb2 as IsomStdDef__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IsomUserMgmt.proto',
  package='Honeywell.Security.ISOM.UserMgmt',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12IsomUserMgmt.proto\x12 Honeywell.Security.ISOM.UserMgmt\x1a\x10IsomStdDef.proto\"o\n\x14\x41uthenticationFactor\x12\x0c\n\x04\x63\x61rd\x18\x0b \x01(\x0c\x12\x0b\n\x03pin\x18\x0c \x01(\x0c\x12\x13\n\x0b\x66ingerPrint\x18\r \x01(\x0c\x12\x10\n\x08password\x18\x0e \x01(\t\x12\x0b\n\x03otp\x18\x0f \x01(\x0c*\x08\x08\xc0\x84=\x10\xe0\x91\x43\"\xfc\x02\n\x0fValidityOptions\x12\r\n\x05valid\x18\x11 \x01(\x08\x12>\n\tvalidFrom\x18\x0b \x01(\x0b\x32%.Honeywell.Security.ISOM.IsomDateTimeB\x04\x90\xb5\x18\r\x12\x1c\n\x14validAfterFirstSwipe\x18\x10 \x01(\x08\x12<\n\x07validTo\x18\x0c \x01(\x0b\x32%.Honeywell.Security.ISOM.IsomDateTimeB\x04\x90\xb5\x18\r\x12G\n\x12maxDurationAllowed\x18\r \x01(\x0b\x32%.Honeywell.Security.ISOM.IsomDurationB\x04\x90\xb5\x18\x11\x12\x1d\n\x15maxNumberTimesAllowed\x18\x0e \x01(\x04\x12L\n\x17inactiveDurationAllowed\x18\x0f \x01(\x0b\x32%.Honeywell.Security.ISOM.IsomDurationB\x04\x90\xb5\x18\x11*\x08\x08\xc0\x84=\x10\xe0\x91\x43')
  ,
  dependencies=[IsomStdDef__pb2.DESCRIPTOR,])




_AUTHENTICATIONFACTOR = _descriptor.Descriptor(
  name='AuthenticationFactor',
  full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='card', full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor.card', index=0,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin', full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor.pin', index=1,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fingerPrint', full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor.fingerPrint', index=2,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor.password', index=3,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='otp', full_name='Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor.otp', index=4,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000000, 1100000), ],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=185,
)


_VALIDITYOPTIONS = _descriptor.Descriptor(
  name='ValidityOptions',
  full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.valid', index=0,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validFrom', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.validFrom', index=1,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\r'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validAfterFirstSwipe', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.validAfterFirstSwipe', index=2,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validTo', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.validTo', index=3,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\r'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxDurationAllowed', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.maxDurationAllowed', index=4,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\021'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxNumberTimesAllowed', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.maxNumberTimesAllowed', index=5,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inactiveDurationAllowed', full_name='Honeywell.Security.ISOM.UserMgmt.ValidityOptions.inactiveDurationAllowed', index=6,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\220\265\030\021'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000000, 1100000), ],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=568,
)

_VALIDITYOPTIONS.fields_by_name['validFrom'].message_type = IsomStdDef__pb2._ISOMDATETIME
_VALIDITYOPTIONS.fields_by_name['validTo'].message_type = IsomStdDef__pb2._ISOMDATETIME
_VALIDITYOPTIONS.fields_by_name['maxDurationAllowed'].message_type = IsomStdDef__pb2._ISOMDURATION
_VALIDITYOPTIONS.fields_by_name['inactiveDurationAllowed'].message_type = IsomStdDef__pb2._ISOMDURATION
DESCRIPTOR.message_types_by_name['AuthenticationFactor'] = _AUTHENTICATIONFACTOR
DESCRIPTOR.message_types_by_name['ValidityOptions'] = _VALIDITYOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthenticationFactor = _reflection.GeneratedProtocolMessageType('AuthenticationFactor', (_message.Message,), {
  'DESCRIPTOR' : _AUTHENTICATIONFACTOR,
  '__module__' : 'IsomUserMgmt_pb2'
  # @@protoc_insertion_point(class_scope:Honeywell.Security.ISOM.UserMgmt.AuthenticationFactor)
  })
_sym_db.RegisterMessage(AuthenticationFactor)

ValidityOptions = _reflection.GeneratedProtocolMessageType('ValidityOptions', (_message.Message,), {
  'DESCRIPTOR' : _VALIDITYOPTIONS,
  '__module__' : 'IsomUserMgmt_pb2'
  # @@protoc_insertion_point(class_scope:Honeywell.Security.ISOM.UserMgmt.ValidityOptions)
  })
_sym_db.RegisterMessage(ValidityOptions)


_VALIDITYOPTIONS.fields_by_name['validFrom']._options = None
_VALIDITYOPTIONS.fields_by_name['validTo']._options = None
_VALIDITYOPTIONS.fields_by_name['maxDurationAllowed']._options = None
_VALIDITYOPTIONS.fields_by_name['inactiveDurationAllowed']._options = None
# @@protoc_insertion_point(module_scope)
