# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyPads_e.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IsomStdDef_pb2 as IsomStdDef__pb2
import KeyPads_pb2 as KeyPads__pb2
import IsomPeripheral_pb2 as IsomPeripheral__pb2
import DetectorGroups_pb2 as DetectorGroups__pb2
import IsomDeviceCollections_pb2 as IsomDeviceCollections__pb2
import IsomAccessPoints_pb2 as IsomAccessPoints__pb2
import KeySwitches_pb2 as KeySwitches__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='KeyPads_e.proto',
  package='Honeywell.Security.ISOM.KeyPads',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fKeyPads_e.proto\x12\x1fHoneywell.Security.ISOM.KeyPads\x1a\x10IsomStdDef.proto\x1a\rKeyPads.proto\x1a\x14IsomPeripheral.proto\x1a\x14\x44\x65tectorGroups.proto\x1a\x1bIsomDeviceCollections.proto\x1a\x16IsomAccessPoints.proto\x1a\x11KeySwitches.proto\"\xfe\x05\n\x0eKeyPadConfig_e2\x8f\x01\n\x1a\x44\x65viceAssignedToPeripheral\x12-.Honeywell.Security.ISOM.KeyPads.KeyPadConfig\x18\xa1\xf7\x36 \x03(\x0b\x32\x34.Honeywell.Security.ISOM.Peripheral.PeripheralConfigB\x04\xa0\xb5\x18\x01\x32\xa2\x01\n DeviceAssignedToDeviceCollection\x12-.Honeywell.Security.ISOM.KeyPads.KeyPadConfig\x18\xa2\xf7\x36 \x03(\x0b\x32\x41.Honeywell.Security.ISOM.DeviceCollections.DeviceCollectionConfigB\x04\xa0\xb5\x18\x01\x32\x99\x01\n\x1d\x44\x65viceAssignedToDetectorGroup\x12-.Honeywell.Security.ISOM.KeyPads.KeyPadConfig\x18\xa3\xf7\x36 \x03(\x0b\x32;.Honeywell.Security.ISOM.DetectorGroups.DetectorGroupConfigB\x04\xa0\xb5\x18\x01\x32\x8e\x01\n\x1fKeyPadAssociatedWithAccessPoint\x12-.Honeywell.Security.ISOM.KeyPads.KeyPadConfig\x18\xa4\xf7\x36 \x03(\x0b\x32..Honeywell.Security.ISOM.AccessPoints.APConfigB\x04\xa0\xb5\x18\x01\x32\x87\x01\n\x12KeypadHasKeySwitch\x12-.Honeywell.Security.ISOM.KeyPads.KeyPadConfig\x18\xa5\xf7\x36 \x03(\x0b\x32\x34.Honeywell.Security.ISOM.KeySwitches.KeySwitchConfigB\x04\xa0\xb5\x18\x01')
  ,
  dependencies=[IsomStdDef__pb2.DESCRIPTOR,KeyPads__pb2.DESCRIPTOR,IsomPeripheral__pb2.DESCRIPTOR,DetectorGroups__pb2.DESCRIPTOR,IsomDeviceCollections__pb2.DESCRIPTOR,IsomAccessPoints__pb2.DESCRIPTOR,KeySwitches__pb2.DESCRIPTOR,])




_KEYPADCONFIG_E = _descriptor.Descriptor(
  name='KeyPadConfig_e',
  full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='DeviceAssignedToPeripheral', full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e.DeviceAssignedToPeripheral', index=0,
      number=900001, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceAssignedToDeviceCollection', full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e.DeviceAssignedToDeviceCollection', index=1,
      number=900002, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceAssignedToDetectorGroup', full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e.DeviceAssignedToDetectorGroup', index=2,
      number=900003, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='KeyPadAssociatedWithAccessPoint', full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e.KeyPadAssociatedWithAccessPoint', index=3,
      number=900004, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='KeypadHasKeySwitch', full_name='Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e.KeypadHasKeySwitch', index=4,
      number=900005, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=_b('\240\265\030\001'), file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=968,
)

DESCRIPTOR.message_types_by_name['KeyPadConfig_e'] = _KEYPADCONFIG_E
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyPadConfig_e = _reflection.GeneratedProtocolMessageType('KeyPadConfig_e', (_message.Message,), {
  'DESCRIPTOR' : _KEYPADCONFIG_E,
  '__module__' : 'KeyPads_e_pb2'
  # @@protoc_insertion_point(class_scope:Honeywell.Security.ISOM.KeyPads.KeyPadConfig_e)
  })
_sym_db.RegisterMessage(KeyPadConfig_e)

_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToPeripheral'].message_type = IsomPeripheral__pb2._PERIPHERALCONFIG
KeyPads__pb2.KeyPadConfig.RegisterExtension(_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToPeripheral'])
_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDeviceCollection'].message_type = IsomDeviceCollections__pb2._DEVICECOLLECTIONCONFIG
KeyPads__pb2.KeyPadConfig.RegisterExtension(_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDeviceCollection'])
_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDetectorGroup'].message_type = DetectorGroups__pb2._DETECTORGROUPCONFIG
KeyPads__pb2.KeyPadConfig.RegisterExtension(_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDetectorGroup'])
_KEYPADCONFIG_E.extensions_by_name['KeyPadAssociatedWithAccessPoint'].message_type = IsomAccessPoints__pb2._APCONFIG
KeyPads__pb2.KeyPadConfig.RegisterExtension(_KEYPADCONFIG_E.extensions_by_name['KeyPadAssociatedWithAccessPoint'])
_KEYPADCONFIG_E.extensions_by_name['KeypadHasKeySwitch'].message_type = KeySwitches__pb2._KEYSWITCHCONFIG
KeyPads__pb2.KeyPadConfig.RegisterExtension(_KEYPADCONFIG_E.extensions_by_name['KeypadHasKeySwitch'])

_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToPeripheral']._options = None
_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDeviceCollection']._options = None
_KEYPADCONFIG_E.extensions_by_name['DeviceAssignedToDetectorGroup']._options = None
_KEYPADCONFIG_E.extensions_by_name['KeyPadAssociatedWithAccessPoint']._options = None
_KEYPADCONFIG_E.extensions_by_name['KeypadHasKeySwitch']._options = None
# @@protoc_insertion_point(module_scope)
